
		align	4
		label	L832_len__hla_ word
		dd	0eh
		dd	0eh
		label	L832_str__hla_ byte
		db	"Gimme iValue1:"
		db	0

		db	0

		align	4
		label	L854_len__hla_ word
		dd	0eh
		dd	0eh
		label	L854_str__hla_ byte
		db	"Gimme iValue2:"
		db	0

		db	0

		align	4
		label	L876_len__hla_ word
		dd	0eh
		dd	0eh
		label	L876_str__hla_ byte
		db	"Gimme iValue3:"
		db	0

		db	0

		align	4
		label	L898_len__hla_ word
		dd	013h
		dd	013h
		label	L898_str__hla_ byte
		db	"after makeSmallest!"
		db	0


		align	4
		label	L912_len__hla_ word
		dd	0ah
		dd	0ah
		label	L912_str__hla_ byte
		db	"iValue1 = "
		db	0

		db	0

		align	4
		label	L941_len__hla_ word
		dd	01h
		dd	01h
		label	L941_str__hla_ byte
		db	" "
		db	0

		db	0
		db	0

		align	4
		label	L955_len__hla_ word
		dd	0ah
		dd	0ah
		label	L955_str__hla_ byte
		db	"iValue2 = "
		db	0

		db	0

		align	4
		label	L998_len__hla_ word
		dd	0ah
		dd	0ah
		label	L998_str__hla_ byte
		db	"iValue3 = "
		db	0

		db	0
