
		align	4
		label	L826_len__hla_ word
		dd	0fh
		dd	0fh
		label	L826_str__hla_ byte
		db	"Gimme a number:"
		db	0


		align	4
		label	L896_len__hla_ word
		dd	0bh
		dd	0bh
		label	L896_str__hla_ byte
		db	"Crazy Eight"
		db	0


		align	4
		label	L915_len__hla_ word
		dd	05h
		dd	05h
		label	L915_str__hla_ byte
		db	"Eight"
		db	0

		db	0
		db	0

		align	4
		label	L933_len__hla_ word
		dd	0eh
		dd	0eh
		label	L933_str__hla_ byte
		db	"program6 Over!"
		db	0

		db	0

		align	4
		label	L951_len__hla_ word
		dd	07h
		dd	07h
		label	L951_str__hla_ byte
		db	"Score= "
		db	0

