
		align	4
		label	L835_len__hla_ word
		dd	09h
		dd	09h
		label	L835_str__hla_ byte
		db	"Gimme X: "
		db	0

		db	0
		db	0

		align	4
		label	L857_len__hla_ word
		dd	09h
		dd	09h
		label	L857_str__hla_ byte
		db	"Gimme Y: "
		db	0

		db	0
		db	0

		align	4
		label	L879_len__hla_ word
		dd	09h
		dd	09h
		label	L879_str__hla_ byte
		db	"Gimme Z: "
		db	0

		db	0
		db	0

		align	4
		label	L901_len__hla_ word
		dd	013h
		dd	013h
		label	L901_str__hla_ byte
		db	"After sorting, X = "
		db	0


		align	4
		label	L915_len__hla_ word
		dd	06h
		dd	06h
		label	L915_str__hla_ byte
		db	", Y = "
		db	0

		db	0

		align	4
		label	L929_len__hla_ word
		dd	06h
		dd	06h
		label	L929_str__hla_ byte
		db	", Z = "
		db	0

		db	0
