
		align	4
		label	L824_len__hla_ word
		dd	017h
		dd	017h
		label	L824_str__hla_ byte
		db	"What's in your wallet: "
		db	0


		align	4
		label	L846_len__hla_ word
		dd	08h
		dd	08h
		label	L846_str__hla_ byte
		db	"This is "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L860_len__hla_ word
		dd	014h
		dd	014h
		label	L860_str__hla_ byte
		db	" in British pounds"
		db	0dh
		db	0ah
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L888_len__hla_ word
		dd	013h
		dd	013h
		label	L888_str__hla_ byte
		db	" in Mexican pesos"
		db	0dh
		db	0ah
		db	0

