
		align	4
		label	L821_len__hla_ word
		dd	018h
		dd	018h
		label	L821_str__hla_ byte
		db	"Gimme a starting value: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L849_len__hla_ word
		dd	02h
		dd	02h
		label	L849_str__hla_ byte
		db	": "
		db	0

		db	0

		align	4
		label	L869_len__hla_ word
		dd	01h
		dd	01h
		label	L869_str__hla_ byte
		db	" "
		db	0

		db	0
		db	0
