
		align	4
		label	L828_len__hla_ word
		dd	015h
		dd	015h
		label	L828_str__hla_ byte
		db	"Gimme a value for a: "
		db	0

		db	0
		db	0

		align	4
		label	L850_len__hla_ word
		dd	015h
		dd	015h
		label	L850_str__hla_ byte
		db	"Gimme a value for b: "
		db	0

		db	0
		db	0

		align	4
		label	L872_len__hla_ word
		dd	015h
		dd	015h
		label	L872_str__hla_ byte
		db	"Gimme a value for c: "
		db	0

		db	0
		db	0

		align	4
		label	L894_len__hla_ word
		dd	016h
		dd	016h
		label	L894_str__hla_ byte
		db	"The solutions are x = "
		db	0

		db	0

		align	4
		label	L908_len__hla_ word
		dd	09h
		dd	09h
		label	L908_str__hla_ byte
		db	" and x = "
		db	0

		db	0
		db	0
