
		align	4
		label	L819_len__hla_ word
		dd	02eh
		dd	02eh
		label	L819_str__hla_ byte
		db	"Feed me(4 hex digits ending with srttccbbmm): "
		db	0

		db	0

		align	4
		label	L842_len__hla_ word
		dd	0ah
		dd	0ah
		label	L842_str__hla_ byte
		db	"No sunroof"
		db	0

		db	0

		align	4
		label	L861_len__hla_ word
		dd	07h
		dd	07h
		label	L861_str__hla_ byte
		db	"Sunroof"
		db	0


		align	4
		label	L880_len__hla_ word
		dd	0bh
		dd	0bh
		label	L880_str__hla_ byte
		db	"No roofrack"
		db	0


		align	4
		label	L899_len__hla_ word
		dd	08h
		dd	08h
		label	L899_str__hla_ byte
		db	"Roofrack"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L918_len__hla_ word
		dd	08h
		dd	08h
		label	L918_str__hla_ byte
		db	"18 inch "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L934_len__hla_ word
		dd	08h
		dd	08h
		label	L934_str__hla_ byte
		db	"19 inch "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L949_len__hla_ word
		dd	08h
		dd	08h
		label	L949_str__hla_ byte
		db	"20 inch "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L963_len__hla_ word
		dd	08h
		dd	08h
		label	L963_str__hla_ byte
		db	"21 inch "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L978_len__hla_ word
		dd	05h
		dd	05h
		label	L978_str__hla_ byte
		db	"blue "
		db	0

		db	0
		db	0

		align	4
		label	L994_len__hla_ word
		dd	04h
		dd	04h
		label	L994_str__hla_ byte
		db	"red "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1009_len__hla_ word
		dd	06h
		dd	06h
		label	L1009_str__hla_ byte
		db	"white "
		db	0

		db	0

		align	4
		label	L1023_len__hla_ word
		dd	06h
		dd	06h
		label	L1023_str__hla_ byte
		db	"black "
		db	0

		db	0

		align	4
		label	L1038_len__hla_ word
		dd	07h
		dd	07h
		label	L1038_str__hla_ byte
		db	"60 kwH "
		db	0


		align	4
		label	L1054_len__hla_ word
		dd	07h
		dd	07h
		label	L1054_str__hla_ byte
		db	"75 kwH "
		db	0


		align	4
		label	L1069_len__hla_ word
		dd	07h
		dd	07h
		label	L1069_str__hla_ byte
		db	"85 kwH "
		db	0


		align	4
		label	L1083_len__hla_ word
		dd	08h
		dd	08h
		label	L1083_str__hla_ byte
		db	"100 kwH "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1098_len__hla_ word
		dd	07h
		dd	07h
		label	L1098_str__hla_ byte
		db	"Model S"
		db	0


		align	4
		label	L1114_len__hla_ word
		dd	07h
		dd	07h
		label	L1114_str__hla_ byte
		db	"Model X"
		db	0


		align	4
		label	L1129_len__hla_ word
		dd	07h
		dd	07h
		label	L1129_str__hla_ byte
		db	"Model 3"
		db	0


		align	4
		label	L1143_len__hla_ word
		dd	07h
		dd	07h
		label	L1143_str__hla_ byte
		db	"Model Y"
		db	0

