
		align	4
		label	L828_len__hla_ word
		dd	0eh
		dd	0eh
		label	L828_str__hla_ byte
		db	"Gimme iValue1:"
		db	0

		db	0

		align	4
		label	L850_len__hla_ word
		dd	0eh
		dd	0eh
		label	L850_str__hla_ byte
		db	"Gimme iValue2:"
		db	0

		db	0

		align	4
		label	L872_len__hla_ word
		dd	0eh
		dd	0eh
		label	L872_str__hla_ byte
		db	"Gimme iValue3:"
		db	0

		db	0

		align	4
		label	L894_len__hla_ word
		dd	017h
		dd	017h
		label	L894_str__hla_ byte
		db	"after noneZero iAnswer="
		db	0

